version: "3.9"

services:
  weather_app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/weather_app
    ports:
      - "8000:8000"
    env_file:
      - ../.env